# This file configures the egen-capstone app which serves public web traffic .
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egen-capstone2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: egen-capstone-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-west2-docker.pkg.dev/capstone1-project-326220/capstone-repo/egen-capstone2:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
